version: "3.2"

services:
  acestream-server:
    container_name: acestream-server
    restart: always
    ports:
      - "${ACE_API_PORT}:6878"
      - "8621:8621"
    volumes:
      - ./config/acestream.conf:/ace/config/acestream.conf
      - ./logs:/ace/logs
      - "/etc/timezone:/etc/timezone:ro"
    env_file:
      - ./.env
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - ACE_STREAM_VERSION=$ACE_STREAM_VERSION

  acestream-web:
    container_name: acestream-web
    restart: always
    ports:
      - "4000:5000"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
    env_file:
      - ./.env
    build:
      dockerfile: ./dockerfile-web
    depends_on:
      acestream-server:
        condition: service_started
