version: "3.2"

services:
  acestream-server:
    container_name: acestream-server
    restart: always
    ports:
      - "${ACE_PLAYER_PORT}:6878"
      - "${ACE_API_PORT}:7000"
    volumes:
      - ./config/acestream.conf:/acestream.conf
      - ./logs:/logs
    env_file:
      - ./.env
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - ACE_STREAM_VERSION=$ACE_STREAM_VERSION
